### ISSUE TITLE
Zoom on Microsoft Edge - Need Leaflet 1.7.1

### ISSUE THREAD

**Issue by 123gizi** [bmcbride/gps-map#2]
Love this project. Thanks heaps for sharing.
Pinch zoom doesn't work on Windows 10 Edge browser but Leaflet 1.7.1 appears to resolve this issue.
I know you had issue with Safari on 1.7.1 but thought I'd mention it.

Random request (because I don't know how), is there a way to to have the app on start up, load all files in for example /assets/overlays or an option import a local directory filled with multiple files such as KMLs?

Thanks.

**Comment by bmcbride** [comment]
Leaflet has been updated to 1.7.1 and I reimplemented file saving, so any MBTiles / vector files loaded into the app will be available in the layer control the next time it loads.
