### ISSUE TITLE
Simple way to experiment without internet connexion

### ISSUE THREAD

**Issue by MENIER** [bmcbride/gps-map#3]
Hello,
I have download your source and click on index.html and add my mbtiles file...with no result
I tested https://gpsmap.app/ and  add my mbtiles file...successful but I don't fine where is my mbtiles in local cache...
It s possible install with no internet access?
Thanks

**Comment by bmcbride** [comment]
The app needs to be loaded from a web server. If you are still experimenting, please note the change from MBTiles to PMTiles.
